apiVersion : apps/v1
kind: Deployment
metadata:
  name: "adv-32a8"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "adv-32a8"
  template:
    metadata:
      labels:
        app: "adv-32a8"
    spec:
      containers:
        - name: "adv-32a8"
          image: "advregin.azurecr.io/adv"
          ports:
          - containerPort: 80