on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: advregin.azurecr.io
        username: ${{ secrets.acr_advregin_username }}
        password: ${{ secrets.acr_advregin_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t advregin.azurecr.io/adv:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push advregin.azurecr.io/adv:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_adv_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep advnm | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace advnm`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: advnm
        container-registry-url: advregin.azurecr.io
        container-registry-username: ${{ secrets.acr_advregin_username }}
        container-registry-password: ${{ secrets.acr_advregin_password }}
        secret-name: advdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: advnm
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          advregin.azurecr.io/adv:${{ github.sha }}
        imagepullsecrets: |
          advdockerauth
